name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Используем стабильную версию
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4  # Версия 4 использует Node.js 16
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev \
          python3-pip
        pip3 install --upgrade pip
        pip3 install buildozer
    
    - name: Build APK
      run: |
        buildozer android debug deploy
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Tamagotchi-APK
        path: bin/*.apk
